### PR TITLE
Fix a few things for running libfuzzer.

### PR DESCRIPTION
**Pull request by wuestholz**

### CODE REVIEW

**Review by ScottWe — COMMENTED** [review]
Might it be better to remove those logs entirely?

**Comment by wuestholz** [comment]
Yeah, I don't have a strong opinion. I assumed that Xinwen added them to debug. Maybe we could add a define?

**Comment by ScottWe** [comment]
They looked copied/pasted from my interactive implementation. I thought maybe they were just artifacts of that. If Xinwen wants them, I'll merge as is. 👍 I'll follow up with her.

**Comment by wuestholz** [comment]
Sounds good. 👍

**Pull request merged**
